"""Shared machinery for the worklist scripts.

Everything is derived from the two quaternion generators; no tables are used.

Conventions (see worklist.md section 1):
  * spins are integers here except where a doubled spin `tj` is used for D-matrices;
  * a vector in V_j is a list of length 2j+1, index i <-> weight m = i - j;
  * D^j(g) is built from the 2x2 matrix g = [[a,b],[c,d]] by the substitution
    x -> a x + c y, y -> b x + d y on v_m = x^(j+m) y^(j-m)/sqrt((j+m)!(j-m)!),
    which gives D^(1/2)(g) = g and the Condon-Shortley J_+ (checked in item0/item1);
  * a section at level 2J is stored as {J: [u_0, u_1, ...]} with one fibre vector per
    kept intertwiner eta_J[gamma]; the section is sum_gamma u_gamma (x) eta_J[gamma];
  * a right-Gamma-invariant scalar function is stored as {K: [(s, r), ...]}, meaning
    sum s_M D^K_{MK'}(g) r_K'.
"""
import os, sys, json
from fractions import Fraction
from math import factorial as fac, comb
from mpmath import mp, mpf, mpc

HERE = os.path.dirname(os.path.abspath(__file__))
RESULTS_DIR = os.path.join(HERE, 'results')


# ----------------------------------------------------------------------------------
# exact arithmetic in Q(sqrt5) and quaternions over it
# ----------------------------------------------------------------------------------
class Q5:
    """a + b*sqrt(5), a, b rational."""
    __slots__ = ('a', 'b')

    def __init__(self, a, b=0):
        self.a = Fraction(a)
        self.b = Fraction(b)

    def __add__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return Q5(s.a + o.a, s.b + o.b)
    __radd__ = __add__

    def __sub__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return Q5(s.a - o.a, s.b - o.b)

    def __rsub__(s, o):
        return Q5(o) - s

    def __neg__(s):
        return Q5(-s.a, -s.b)

    def __mul__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return Q5(s.a * o.a + 5 * s.b * o.b, s.a * o.b + s.b * o.a)
    __rmul__ = __mul__

    def __truediv__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        n = o.a * o.a - 5 * o.b * o.b
        return s * Q5(o.a / n, -o.b / n)

    def __eq__(s, o):
        o = o if isinstance(o, Q5) else Q5(o)
        return s.a == o.a and s.b == o.b

    def __hash__(s):
        return hash((s.a, s.b))

    def to_mp(s):
        return mpf(s.a.numerator) / s.a.denominator + mpf(s.b.numerator) / s.b.denominator * mp.sqrt(5)

    def __repr__(s):
        if s.b == 0:
            return str(s.a)
        if s.a == 0:
            return '(%s*sqrt(5))' % s.b
        return '(%s%s%s*sqrt(5))' % (s.a, '+' if s.b > 0 else '-', abs(s.b))


PHI = Q5(Fraction(1, 2), Fraction(1, 2))
PHI_INV = PHI - 1


def qmul(p, q):
    w1, x1, y1, z1 = p
    w2, x2, y2, z2 = q
    return (w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
            w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
            w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
            w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2)


def qinv(p):  # unit quaternions only
    return (p[0], -p[1], -p[2], -p[3])


def qnorm2(p):
    return p[0] * p[0] + p[1] * p[1] + p[2] * p[2] + p[3] * p[3]


HALF = Fraction(1, 2)
Q1 = (Q5(HALF), Q5(HALF), Q5(HALF), Q5(HALF))
Q2 = (PHI * HALF, PHI_INV * HALF, Q5(HALF), Q5(0))
ONE = (Q5(1), Q5(0), Q5(0), Q5(0))


def closure(gens):
    """Group generated by `gens` (finite), by breadth-first multiplication."""
    elems = [ONE]
    seen = {ONE}
    frontier = [ONE]
    while frontier:
        new = []
        for e in frontier:
            for g in gens:
                h = qmul(e, g)
                if h not in seen:
                    seen.add(h)
                    elems.append(h)
                    new.append(h)
        frontier = new
    return elems


_GROUP = None


def group():
    global _GROUP
    if _GROUP is None:
        _GROUP = closure([Q1, Q2])
    return _GROUP


def chebU(n, w):
    """Chebyshev U_n(w) exactly (w in Q5); trace of D^{n/2} at an element with real part w."""
    if n == 0:
        return Q5(1)
    a, b = Q5(1), 2 * w
    for _ in range(n - 1):
        a, b = b, 2 * w * b - a
    return b


# ----------------------------------------------------------------------------------
# quaternion -> SU(2) identifications
# ----------------------------------------------------------------------------------
def quat_to_su2(q, ident='A'):
    """ident A: i,j,k -> -i sigma_x, -i sigma_y, -i sigma_z.
       ident B: i,j,k ->  i sigma_z,  i sigma_y,  i sigma_x (orientation of the axes swapped)."""
    w, x, y, z = [c.to_mp() if isinstance(c, Q5) else mpf(c) for c in q]
    I = mpc(0, 1)
    if ident == 'A':
        return [[w - I * z, -y - I * x], [y - I * x, w + I * z]]
    if ident == 'B':
        # w + x(i s_z) + y(i s_y) + z(i s_x)
        return [[w + I * x, y + I * z], [-y + I * z, w - I * x]]
    raise ValueError(ident)


# ----------------------------------------------------------------------------------
# Clebsch-Gordan coefficients, exact (Racah formula), integer spins
# ----------------------------------------------------------------------------------
_CG_EXACT = {}


def cg_exact(j1, m1, j2, m2, J, M):
    """Return (sign, value^2) with value = sign*sqrt(value^2), Condon-Shortley convention."""
    key = (j1, m1, j2, m2, J, M)
    if key in _CG_EXACT:
        return _CG_EXACT[key]
    if (m1 + m2 != M or not (abs(j1 - j2) <= J <= j1 + j2) or abs(m1) > j1 or abs(m2) > j2
            or abs(M) > J):
        res = (0, Fraction(0))
    else:
        pref = Fraction((2 * J + 1) * fac(J + j1 - j2) * fac(J - j1 + j2) * fac(j1 + j2 - J),
                        fac(j1 + j2 + J + 1))
        pref *= fac(J + M) * fac(J - M) * fac(j1 - m1) * fac(j1 + m1) * fac(j2 - m2) * fac(j2 + m2)
        S = Fraction(0)
        for k in range(0, j1 + j2 - J + 1):
            den = [k, j1 + j2 - J - k, j1 - m1 - k, j2 + m2 - k, J - j2 + m1 + k, J - j1 - m2 + k]
            if min(den) < 0:
                continue
            p = 1
            for x in den:
                p *= fac(x)
            S += Fraction((-1) ** k, p)
        res = ((S > 0) - (S < 0), pref * S * S)
    _CG_EXACT[key] = res
    return res


_CG_MP = {}


def cg(j1, m1, j2, m2, J, M):
    key = (mp.prec, j1, m1, j2, m2, J, M)
    v = _CG_MP.get(key)
    if v is None:
        s, v2 = cg_exact(j1, m1, j2, m2, J, M)
        v = mpf(0) if s == 0 else s * mp.sqrt(mpf(v2.numerator) / v2.denominator)
        _CG_MP[key] = v
    return v


_COUPLE_TAB = {}


def couple_table(j1, j2, J):
    key = (mp.prec, j1, j2, J)
    t = _COUPLE_TAB.get(key)
    if t is None:
        t = []
        for M in range(-J, J + 1):
            row = []
            for m1 in range(-j1, j1 + 1):
                m2 = M - m1
                if abs(m2) <= j2:
                    c = cg(j1, m1, j2, m2, J, M)
                    if c != 0:
                        row.append((m1 + j1, m2 + j2, c))
            t.append(row)
        _COUPLE_TAB[key] = t
    return t


def couple(x, j1, y, j2, J):
    """[x (x) y]_J."""
    t = couple_table(j1, j2, J)
    return [mp.fsum(c * x[i1] * y[i2] for (i1, i2, c) in row) if row else mpc(0) for row in t]


# ----------------------------------------------------------------------------------
# vectors, time reversal, D-matrices
# ----------------------------------------------------------------------------------
def theta(x):
    """Theta(sum u_m v_m) = sum (-1)^m conj(u_m) v_{-m} on V_j, j integer."""
    j = (len(x) - 1) // 2
    return [((-1) ** (m % 2)) * mp.conj(x[-m + j]) for m in range(-j, j + 1)]


def vdot(x, y):  # <x,y>, antilinear in x
    return mp.fsum(mp.conj(a) * b for a, b in zip(x, y))


def vnorm2(x):
    return mp.fsum(abs(a) ** 2 for a in x)


def vadd(x, y, c=1):
    return [a + c * b for a, b in zip(x, y)]


def vscale(x, c):
    return [c * a for a in x]


def basis_vec(j, m):
    v = [mpc(0)] * (2 * j + 1)
    v[m + j] = mpc(1)
    return v


def wigner_D(tj, g):
    """D^{tj/2}(g) as a list of rows, index i = (tm + tj)/2 for tm = -tj, -tj+2, ..., tj."""
    a, b = g[0]
    c, d = g[1]
    n = tj
    D = [[mpc(0)] * (n + 1) for _ in range(n + 1)]
    apow = [mpc(1)]
    bpow = [mpc(1)]
    cpow = [mpc(1)]
    dpow = [mpc(1)]
    for _ in range(n):
        apow.append(apow[-1] * a)
        bpow.append(bpow[-1] * b)
        cpow.append(cpow[-1] * c)
        dpow.append(dpow[-1] * d)
    for ip in range(n + 1):  # column: v_{m'} with p = j+m' = ip, q = n - ip
        p, q = ip, n - ip
        for r in range(n + 1):  # row: v_m with r = j+m
            s = mpc(0)
            for k in range(max(0, r - q), min(p, r) + 1):
                l = r - k
                s += comb(p, k) * comb(q, l) * apow[k] * cpow[p - k] * bpow[l] * dpow[q - l]
            D[r][ip] = s * mp.sqrt(mpf(fac(r) * fac(n - r)) / (fac(p) * fac(q)))
    return D


def mat_mul(A, B):
    n, k, m = len(A), len(B), len(B[0])
    return [[mp.fsum(A[i][t] * B[t][j] for t in range(k)) for j in range(m)] for i in range(n)]


def mat_vec(A, x):
    return [mp.fsum(a * b for a, b in zip(row, x)) for row in A]


def mat_adj(A):
    return [[mp.conj(A[i][j]) for i in range(len(A))] for j in range(len(A[0]))]


def mat_conj(A):
    return [[mp.conj(a) for a in row] for row in A]


def mat_maxdiff(A, B):
    return max(abs(a - b) for ra, rb in zip(A, B) for a, b in zip(ra, rb))


def col(A, a):
    return [row[a] for row in A]


def spin_matrices(j):
    """Explicit J_x, J_y, J_z on V_j (Condon-Shortley J_+)."""
    n = 2 * j + 1
    Jp = [[mpc(0)] * n for _ in range(n)]
    Jz = [[mpc(0)] * n for _ in range(n)]
    for m in range(-j, j + 1):
        Jz[m + j][m + j] = mpc(m)
        if m < j:
            Jp[m + 1 + j][m + j] = mpc(mp.sqrt((j - m) * (j + m + 1)))
    Jm = mat_adj(Jp)
    Jx = [[(Jp[i][k] + Jm[i][k]) / 2 for k in range(n)] for i in range(n)]
    Jy = [[(Jp[i][k] - Jm[i][k]) / mpc(0, 2) for k in range(n)] for i in range(n)]
    return Jx, Jy, Jz


# ----------------------------------------------------------------------------------
# the sectors: decomposition of V_3, sigma, intertwiners at every level
# ----------------------------------------------------------------------------------
def _pseudo_random_matrix(n, m, seed):
    # deterministic, reproducible "generic" entries
    out = []
    for i in range(n):
        row = []
        for k in range(m):
            t = (seed * 7919 + i * 104729 + k * 1299709) % 1000003
            u = (seed * 31 + i * 17 + k * 13 + 5) % 997
            row.append(mpc(mpf(t) / 1000003 - mpf(1) / 2, mpf(u) / 997 - mpf(1) / 3))
        out.append(row)
    return out


def gram_schmidt_frob(mats, d, tol):
    """Orthonormalise (2J+1) x d matrices so that eta^dagger eta = I and eta^dagger eta' = 0
    (by Schur these are multiples of I, so Frobenius orthogonality suffices)."""
    basis = []
    for X in mats:
        Y = [row[:] for row in X]
        for B in basis:
            c = mp.fsum(mp.conj(b) * y for rb, ry in zip(B, Y) for b, y in zip(rb, ry)) / d
            Y = [[y - c * b for y, b in zip(ry, rb)] for ry, rb in zip(Y, B)]
        nrm = mp.sqrt(mp.fsum(abs(y) ** 2 for ry in Y for y in ry) / d)
        if nrm > tol:
            basis.append([[y / nrm for y in ry] for ry in Y])
    return basis


def theta_cols(X):
    n = len(X)
    d = len(X[0])
    cols = [theta(col(X, a)) for a in range(d)]
    return [[cols[a][i] for a in range(d)] for i in range(n)]


class Setup:
    """All Gamma-dependent data at the current mp precision."""

    def __init__(self, ident='A', jmax=9):
        self.ident = ident
        self.jmax = jmax
        self.G = group()
        self.su2 = [quat_to_su2(h, ident) for h in self.G]
        self.idx_q1 = self.G.index(Q1)
        self.idx_q2 = self.G.index(Q2)
        self.Dcache = {}
        self.tol = mpf(10) ** (-(mp.dps // 2))
        self._decompose_V3()
        self.sectors = {}
        for name in ('3', '4'):
            self.sectors[name] = Sector(self, name)

    def D(self, j, i):
        key = (j, i)
        if key not in self.Dcache:
            self.Dcache[key] = wigner_D(2 * j, self.su2[i])
        return self.Dcache[key]

    def _decompose_V3(self):
        n = len(self.G)
        M = _pseudo_random_matrix(7, 7, 1)
        M = [[(M[i][k] + mp.conj(M[k][i])) / 2 for k in range(7)] for i in range(7)]
        C = [[mpc(0)] * 7 for _ in range(7)]
        for i in range(n):
            D = self.D(3, i)
            T = mat_mul(mat_mul(D, M), mat_adj(D))
            C = [[C[r][s] + T[r][s] / n for s in range(7)] for r in range(7)]
        E, Q = mp.eighe(mp.matrix(C))
        ev = [E[k] for k in range(7)]
        # cluster eigenvalues
        groups = []
        for k in range(7):
            for gp in groups:
                if abs(ev[gp[0]] - ev[k]) < self.tol:
                    gp.append(k)
                    break
            else:
                groups.append([k])
        self.commutant_eigen_groups = [(ev[g[0]], len(g)) for g in groups]
        self.projectors = {}
        for gp in groups:
            P = [[mp.fsum(Q[r, k] * mp.conj(Q[s, k]) for k in gp) for s in range(7)] for r in range(7)]
            self.projectors[str(len(gp))] = P


class Sector:
    def __init__(self, S, name):
        self.S = S
        self.name = name
        P = S.projectors[name]
        d = int(name)
        self.d = d
        # Theta-real orthonormal basis of the constituent
        cand = []
        for k in range(7):
            x = [P[r][k] for r in range(7)]
            for y in (vadd(x, theta(x)), vscale(vadd(x, theta(x), -1), mpc(0, 1))):
                cand.append([[c] for c in y])
        vecs = gram_schmidt_frob(cand, 1, S.tol)[:d]
        self.eta3 = [[vecs[a][r][0] for a in range(d)] for r in range(7)]
        # sigma(h) = eta^dagger D^3(h) eta for every element
        self.sigma = [mat_mul(mat_adj(self.eta3), mat_mul(S.D(3, i), self.eta3)) for i in range(len(S.G))]
        self.eta = {}
        self.eta[3] = [self.eta3]
        for J in range(0, S.jmax + 1):
            if J == 3:
                continue
            self.eta[J] = self._intertwiners(J)
        self._rs = {}
        self._mc = {}
        self.max_expand_residual = mpf(0)
        self.max_dropped_r = mpf(0)

    def _intertwiners(self, J):
        S = self.S
        n = 2 * J + 1
        d = self.d
        imgs = []
        for seed in range(1, 4):
            X = _pseudo_random_matrix(n, d, 100 * J + seed)
            R = [[mpc(0)] * d for _ in range(n)]
            for i in range(len(S.G)):
                T = mat_mul(mat_mul(S.D(J, i), X), mat_adj(self.sigma[i]))
                R = [[R[r][a] + T[r][a] for a in range(d)] for r in range(n)]
            R = [[x / len(S.G) for x in row] for row in R]
            imgs.append(R)
            # Theta-real combinations
        real = []
        for R in imgs:
            TR = theta_cols(R)
            real.append([[x + y for x, y in zip(r1, r2)] for r1, r2 in zip(R, TR)])
            real.append([[mpc(0, 1) * (x - y) for x, y in zip(r1, r2)] for r1, r2 in zip(R, TR)])
        return gram_schmidt_frob(real, d, S.tol)

    def dim(self, J):
        return len(self.eta.get(J, []))

    # --- Gamma constants ---------------------------------------------------------
    def rs(self, J1, al, J2, be, K):
        """r = sum_a [Theta eta^al_{J1}[:,a] (x) eta^be_{J2}[:,a]]_K (a Gamma-invariant vector in V_K)."""
        key = (J1, al, J2, be, K)
        if key not in self._rs:
            e1 = self.eta[J1][al]
            e2 = self.eta[J2][be]
            r = [mpc(0)] * (2 * K + 1)
            for a in range(self.d):
                r = vadd(r, couple(theta(col(e1, a)), J1, col(e2, a), J2, K))
            self._rs[key] = r
        return self._rs[key]

    def mulcoef(self, rkey, r, K, J2, be, J):
        """[r (x) eta^be_{J2}]_J (columnwise) expanded in the eta_J basis."""
        key = (rkey, J2, be, J)
        if key not in self._mc:
            e2 = self.eta[J2][be]
            cols = [couple(r, K, col(e2, a), J2, J) for a in range(self.d)]
            T = [[cols[a][k] for a in range(self.d)] for k in range(2 * J + 1)]
            coefs = []
            for eg in self.eta.get(J, []):
                c = mp.fsum(mp.conj(eg[k][a]) * T[k][a] for k in range(2 * J + 1) for a in range(self.d)) / self.d
                coefs.append(c)
            # residual of the expansion (must vanish: products of sections are sections)
            res = mpf(0)
            for k in range(2 * J + 1):
                for a in range(self.d):
                    v = T[k][a] - mp.fsum(c * eg[k][a] for c, eg in zip(coefs, self.eta.get(J, [])))
                    res = max(res, abs(v))
            self.max_expand_residual = max(self.max_expand_residual, res)
            self._mc[key] = coefs
        return self._mc[key]

    # --- section algebra -----------------------------------------------------------
    def scal(self, A, B):
        """Pointwise sum_a conj(A_a) B_a as a scalar function {K: [(s, rkey, r)]}."""
        out = {}
        tiny = mpf(10) ** (-(mp.dps - 8))
        for J1, us in A.items():
            for al, u in enumerate(us):
                tu = theta(u)
                for J2, vs in B.items():
                    for be, v in enumerate(vs):
                        for K in range(abs(J1 - J2), J1 + J2 + 1):
                            r = self.rs(J1, al, J2, be, K)
                            nr = mp.sqrt(vnorm2(r))
                            if nr < tiny:
                                self.max_dropped_r = max(self.max_dropped_r, nr)
                                continue
                            s = couple(tu, J1, v, J2, K)
                            out.setdefault(K, []).append((s, ('rs', J1, al, J2, be, K, 0), r))
        return out

    @staticmethod
    def conjf(f):
        out = {}
        for K, lst in f.items():
            out[K] = [(theta(s), rk[:-1] + (1 - rk[-1],), theta(r)) for (s, rk, r) in lst]
        return out

    @staticmethod
    def addf(f, h):
        out = {K: list(v) for K, v in f.items()}
        for K, v in h.items():
            out.setdefault(K, []).extend(v)
        return out

    def mul(self, f, B, Jset):
        out = {J: [[mpc(0)] * (2 * J + 1) for _ in self.eta[J]] for J in Jset if self.dim(J) > 0}
        for K, lst in f.items():
            for (s, rk, r) in lst:
                for J2, vs in B.items():
                    for be, v in enumerate(vs):
                        for J in out:
                            if not (abs(K - J2) <= J <= K + J2):
                                continue
                            coefs = self.mulcoef(rk, r, K, J2, be, J)
                            if all(abs(c) == 0 for c in coefs):
                                continue
                            left = couple(s, K, v, J2, J)
                            for g_, c in enumerate(coefs):
                                out[J][g_] = vadd(out[J][g_], left, c)
        return out

    def N(self, Phi, Jset=range(0, 10)):
        return self.mul(self.scal(Phi, Phi), Phi, Jset)

    def DN(self, Phi, h, Jset=(3,)):
        sp = self.scal(Phi, h)
        f = self.addf(sp, self.conjf(sp))
        a = self.mul(f, Phi, Jset)
        b = self.mul(self.scal(Phi, Phi), h, Jset)
        return sec_add(a, b)

    def inner(self, A, B):
        s = mpc(0)
        for J in A:
            if J in B:
                for u, v in zip(A[J], B[J]):
                    s += vdot(u, v) * self.d / (2 * J + 1)
        return s

    def norm2(self, A):
        return mp.re(self.inner(A, A))

    def level_norm2(self, A, J):
        return mp.fsum(vnorm2(u) for u in A.get(J, [])) * self.d / (2 * J + 1)

    def block(self, u):
        """Normalized block section of fibre vector u."""
        n2 = vnorm2(u) * self.d / 7
        return {3: [vscale(u, 1 / mp.sqrt(n2))]}


def sec_add(A, B, c=1):
    out = {J: [list(u) for u in us] for J, us in A.items()}
    for J, vs in B.items():
        if J not in out:
            out[J] = [vscale(v, c) for v in vs]
        else:
            out[J] = [vadd(u, v, c) for u, v in zip(out[J], vs)]
    return out


def sec_scale(A, c):
    return {J: [vscale(u, c) for u in us] for J, us in A.items()}


# ----------------------------------------------------------------------------------
# rotations, the left action on fibre vectors, and the stabilizers of item 3
# ----------------------------------------------------------------------------------
def rot(n, th):
    """cos(th/2) I - i sin(th/2) n.sigma  (rotation by th about the unit axis n)."""
    nx, ny, nz = [mpf(x) for x in n]
    nr = mp.sqrt(nx * nx + ny * ny + nz * nz)
    nx, ny, nz = nx / nr, ny / nr, nz / nr
    c, s = mp.cos(mpf(th) / 2), mp.sin(mpf(th) / 2)
    I = mpc(0, 1)
    return [[c - I * s * nz, -I * s * (nx - I * ny)], [-I * s * (nx + I * ny), c + I * s * nz]]


def rho_left(j, g):
    """Left translation on fibre vectors: (r.psi)(g) = psi(r^-1 g)  <=>  u -> conj(D^j(r)) u."""
    return mat_conj(wigner_D(2 * j, g))


def stabilizer_generators():
    """Closed-form generators of the stabilizers found in s03, with the character on Phi.
    Continuous parts are represented by one generic element (angle 1 rad)."""
    pi = mp.pi
    e = lambda x: mp.expjpi(x)  # exp(i pi x)
    return {
        'U1': [(rot((0, 0, 1), 1), mp.exp(mpc(0, 3)))],
        'U2': [(rot((0, 0, 1), 1), mpc(1)), (rot((1, 0, 0), pi), mpc(-1))],
        'U3': [(rot((0, 0, 1), pi / 2), mpc(-1)), (rot((1, 1, 0), pi / 2), mpc(-1))],
        'U4': [(rot((0, 0, 1), pi / 3), mpc(-1)), (rot((1, 0, 0), pi), mpc(-1))],
        'U5': [(rot((0, 0, 1), 2 * pi / 5), e(mpf(4) / 5))],
        'U6': [(rot((0, 0, 1), 2 * pi / 3), mpc(1)), (rot((1, 0, 0), pi), mpc(-1))],
    }


# ----------------------------------------------------------------------------------
# the six fibre vectors (exact data) and helpers
# ----------------------------------------------------------------------------------
def fibre_vectors():
    """mp versions of U1..U6 (unnormalized)."""
    s5 = mp.sqrt(mpf(12) / 25)
    c5 = mp.sqrt(mpf(13) / 25)
    z0 = mp.sqrt(mpf(23) / 10)
    U = {}
    U['U1'] = basis_vec(3, 3)
    U['U2'] = basis_vec(3, 0)
    U['U3'] = vadd(basis_vec(3, 2), basis_vec(3, -2))
    U['U4'] = vadd(basis_vec(3, 3), basis_vec(3, -3))
    U['U5'] = vadd(vscale(basis_vec(3, 2), c5), vscale(basis_vec(3, -3), s5))
    U['U6'] = vadd(vadd(basis_vec(3, 3), basis_vec(3, -3)), vscale(basis_vec(3, 0), z0))
    return U


def tangent_vectors(U):
    """Fibre directions of e_t (at U5) and tau_x (at U6), unnormalized, cf. section 1.6."""
    s5 = mp.sqrt(mpf(12) / 25)
    c5 = mp.sqrt(mpf(13) / 25)
    et = vadd(vscale(basis_vec(3, 2), -s5), vscale(basis_vec(3, -3), c5))
    u6 = U['U6']
    v0 = basis_vec(3, 0)
    tx = vadd(v0, u6, -vdot(u6, v0) / vnorm2(u6))
    return et, tx


# ----------------------------------------------------------------------------------
# identification of exact values from high-precision numerics
# ----------------------------------------------------------------------------------
MAXCOEFF_Q = 10 ** 30      # rational p/q: denominator bound (a spurious convergent would need
                           # |x - p/q| ~ 1/q^2 >= 1e-60, far above the 1e-68 tolerance at 80 digits)
MAXCOEFF_Q5 = 10 ** 10     # relations c0 x + c1 + c2 sqrt5 = 0
PRECISIONS = (80, 120)     # identification precisions (digits)


def _fmt_q5(c0, c1, c2):
    # value = -(c1 + c2 sqrt5)/c0
    a = Fraction(-c1, c0)
    b = Fraction(-c2, c0)
    if b == 0:
        return str(a)
    if a == 0:
        return '%s*sqrt(5)' % b
    return '%s%s%s*sqrt(5)' % (a, '+' if b > 0 else '-', abs(b))


def identify(x, field='Q5'):
    """Find an exact form for real x at the current precision (tolerance 10^-(dps-12)).
    Tries in order: 0; rational (|coefficients| <= 1e20); +-sqrt(rational); Q(sqrt5)
    (|coefficients| <= 1e10); +-sqrt(Q(sqrt5)).  Returns (string, residual) or (None, None)."""
    x = mp.re(x) if isinstance(x, mpc) else x
    tol = mpf(10) ** (-(mp.dps - 12))
    if abs(x) < tol:
        return '0', abs(x)

    def rat(y):
        # continued fraction convergents p/q with q <= MAXCOEFF_Q; accept the first with |y - p/q| < tol
        z = y
        p0, q0, p1, q1 = 0, 1, 1, 0
        for _ in range(200):
            a_ = int(mp.floor(z))
            p0, q0, p1, q1 = p1, q1, a_ * p1 + p0, a_ * q1 + q0
            if q1 > MAXCOEFF_Q:
                return None, None
            if abs(mpf(p1) / q1 - y) < tol * max(1, abs(y)):
                return (q1, -p1, 0), abs(mpf(p1) / q1 - y)
            frac = z - a_
            if frac == 0:
                return None, None
            z = 1 / frac
        return None, None

    def q5(y):
        rel = mp.pslq([y, 1, mp.sqrt(5)], maxcoeff=MAXCOEFF_Q5, maxsteps=200000, tol=tol)
        if rel and rel[0] != 0:
            val = -(rel[1] + rel[2] * mp.sqrt(5)) / rel[0]
            if abs(val - y) < tol * max(1, abs(y)):
                return tuple(rel), abs(val - y)
        return None, None

    sgn = '' if x > 0 else '-'
    rel, res = rat(x)
    if rel:
        return _fmt_q5(*rel), res
    rel, res = rat(x * x)
    if rel:
        return '%ssqrt(%s)' % (sgn, _fmt_q5(*rel)), res
    if field == 'Q5':
        rel, res = q5(x)
        if rel:
            return _fmt_q5(*rel), res
        rel, res = q5(x * x)
        if rel:
            return '%ssqrt(%s)' % (sgn, _fmt_q5(*rel)), res
    return None, None


def save_results(name, data):
    os.makedirs(RESULTS_DIR, exist_ok=True)
    with open(os.path.join(RESULTS_DIR, name + '.json'), 'w') as fh:
        json.dump(data, fh, indent=1, default=str)


def load_results(name):
    with open(os.path.join(RESULTS_DIR, name + '.json')) as fh:
        return json.load(fh)


def check(label, ok, detail=''):
    print(('PASS ' if ok else 'FAIL ') + label + (('  [' + detail + ']') if detail else ''))
    return ok


def nstr(x, n=12):
    return mp.nstr(x, n)
