"""Item 0: norms of the generators, order of Gamma, perfectness, <3 3; 3 -3 | 6 0>.
Also basic checks of the D-matrix and Clebsch-Gordan machinery used everywhere else."""
from common import *
import sympy
from sympy.physics.quantum.cg import CG as SymCG

out = {}
# (a) exact norms
n1, n2 = qnorm2(Q1), qnorm2(Q2)
check('|q1|^2 = 1 exactly', n1 == Q5(1), str(n1))
check('|q2|^2 = 1 exactly', n2 == Q5(1), str(n2))
out['norm2_q1'] = str(n1)
out['norm2_q2'] = str(n2)

G = group()
order = len(G)
print('order of Gamma =', order)
out['order'] = order
# closure really is a group: closed under products and inverses
S = set(G)
closed = all(qmul(a, b) in S for a in G for b in G)
inv = all(qinv(a) in S for a in G)
check('generated set closed under multiplication and inverses', closed and inv)

# derived subgroup: generated by all commutators
comms = set()
for a in G:
    for b in G:
        comms.add(qmul(qmul(a, b), qmul(qinv(a), qinv(b))))
Dsub = closure(list(comms))
print('order of derived subgroup =', len(Dsub))
out['derived_order'] = len(Dsub)
out['perfect'] = (len(Dsub) == order)
print('Gamma equals its derived subgroup:', out['perfect'])

# element orders and conjugacy classes (used in item 1)
def elt_order(q):
    k, p = 1, q
    while p != ONE:
        p = qmul(p, q)
        k += 1
    return k
classes = []
seen = set()
for a in G:
    if a in seen:
        continue
    cl = {qmul(qmul(b, a), qinv(b)) for b in G}
    seen |= cl
    classes.append((elt_order(a), len(cl), a[0]))
classes.sort(key=lambda c: (c[0], str(c[2])))
print('classes (element order, size, real part):', [(o, s, str(w)) for o, s, w in classes])
out['classes'] = [(o, s, str(w)) for o, s, w in classes]
out['center'] = [str(c) for c in G if all(qmul(c, b) == qmul(b, c) for b in G)]
print('centre:', out['center'])

# (b) CG value
s, v2 = cg_exact(3, 3, 3, -3, 6, 0)
val = sympy.sqrt(sympy.Rational(v2.numerator, v2.denominator)) * s
print('<3 3; 3 -3 | 6 0> =', val, '=', sympy.nsimplify(val), ' (squared: %s)' % v2)
out['cg_33_3m3_60'] = str(sympy.radsimp(val))
out['cg_33_3m3_60_squared'] = str(v2)
ref = SymCG(3, 3, 3, -3, 6, 0).doit()
check('Racah-formula CG agrees with sympy for <3 3;3 -3|6 0>', sympy.simplify(ref - val) == 0, str(ref))
check('Condon-Shortley sign: <3 3;3 -3|6 0> > 0', val > 0)

# broader CG cross-check against sympy's independent implementation
bad = 0
cnt = 0
for (j1, j2) in [(3, 3), (6, 3), (3, 2), (5, 4)]:
    for J in range(abs(j1 - j2), j1 + j2 + 1):
        for m1 in range(-j1, j1 + 1):
            for m2 in range(-j2, j2 + 1):
                M = m1 + m2
                if abs(M) > J:
                    continue
                s, v2 = cg_exact(j1, m1, j2, m2, J, M)
                mine = s * sympy.sqrt(sympy.Rational(v2.numerator, v2.denominator))
                if sympy.simplify(SymCG(j1, m1, j2, m2, J, M).doit() - mine) != 0:
                    bad += 1
                cnt += 1
check('Racah CG equals sympy CG on %d coefficients' % cnt, bad == 0, '%d mismatches' % bad)

# D-matrix machinery at 40 digits
mp.dps = 40
g1 = quat_to_su2(Q1)
g2 = quat_to_su2(Q2)
g12 = quat_to_su2(qmul(Q1, Q2))
check('identification A is a homomorphism on q1*q2', mat_maxdiff(mat_mul(g1, g2), g12) < mpf(10) ** -35)
# wigner_D lists weights in ascending order (v_{-1/2}, v_{1/2}); g is written in (v_{1/2}, v_{-1/2})
Dh = wigner_D(1, g2)
check('D^(1/2)(g) = g (after ordering the basis as v_{1/2}, v_{-1/2})',
      mat_maxdiff([[Dh[1][1], Dh[1][0]], [Dh[0][1], Dh[0][0]]], g2) < mpf(10) ** -35)
worst = mpf(0)
for tj in (2, 5, 6, 12):
    worst = max(worst, mat_maxdiff(mat_mul(wigner_D(tj, g1), wigner_D(tj, g2)), wigner_D(tj, g12)))
check('D^j(q1)D^j(q2) = D^j(q1 q2) for j = 1, 5/2, 3, 6', worst < mpf(10) ** -30, nstr(worst, 3))
# J_+ convention: D^j(exp(-i t J_y)) derivative at 0 equals -i J_y
t = mpf(10) ** -15
gy = [[mp.cos(t / 2), -mp.sin(t / 2)], [mp.sin(t / 2), mp.cos(t / 2)]]
Jx, Jy, Jz = spin_matrices(3)
D = wigner_D(6, gy)
gen = [[(D[i][k] - (1 if i == k else 0)) / t for k in range(7)] for i in range(7)]
check('generator of D^3 along y equals -i J_y built from Condon-Shortley J_+',
      mat_maxdiff(gen, [[-mpc(0, 1) * x for x in r] for r in Jy]) < mpf(10) ** -12)
# random element for conj and product formulas
gr = quat_to_su2((Q5(Fraction(3, 10)), Q5(Fraction(-1, 2)), Q5(Fraction(1, 5)), Q5(0)))
nr = mp.sqrt(abs(gr[0][0]) ** 2 + abs(gr[0][1]) ** 2)
gr = [[x / nr for x in row] for row in gr]
D3 = wigner_D(6, gr)
err = max(abs(mp.conj(D3[m + 3][k + 3]) - (-1) ** ((m - k) % 2) * D3[-m + 3][-k + 3])
          for m in range(-3, 4) for k in range(-3, 4))
check('conj D^3_{mk} = (-1)^(m-k) D^3_{-m,-k}', err < mpf(10) ** -35, nstr(err, 3))
D2 = wigner_D(4, gr)
DJ = {J: wigner_D(2 * J, gr) for J in range(1, 6)}
err = mpf(0)
for m1 in range(-3, 4):
    for k1 in range(-3, 4):
        for m2 in range(-2, 3):
            for k2 in range(-2, 3):
                lhs = D3[m1 + 3][k1 + 3] * D2[m2 + 2][k2 + 2]
                rhs = mp.fsum(cg(3, m1, 2, m2, J, m1 + m2) * cg(3, k1, 2, k2, J, k1 + k2) *
                              DJ[J][m1 + m2 + J][k1 + k2 + J]
                              for J in range(1, 6) if abs(m1 + m2) <= J and abs(k1 + k2) <= J)
                err = max(err, abs(lhs - rhs))
check('product formula D^3 D^2 = sum_J CG CG D^J', err < mpf(10) ** -30, nstr(err, 3))
x = [mpc(i + 1, 2 - i) for i in range(7)]
err = max(abs(a - b) for a, b in zip(theta(mat_vec(D3, x)), mat_vec(D3, theta(x))))
check('Theta commutes with D^3(g)', err < mpf(10) ** -35, nstr(err, 3))
save_results('item0', out)
