"""Negative controls: each kind of PASS check used in the other scripts is run on deliberately
corrupted input and must report failure.  A line 'PASS negative control: ...' means the corrupted
input was detected (the underlying check returned False); it would print FAIL if the check had
no power to detect the corruption."""
from common import *
from s04_pipeline import analyze, left_act, sec_maxdiff, mu
from s12_quadrature import make_grid, project_quadrature, tensor_of, tmax, tsub, minus_laplacian, REQ

out = {}


def neg(label, check_result):
    ok = (check_result is False)
    print(('PASS' if ok else 'FAIL') + ' negative control: ' + label)
    out[label] = ok
    return ok


# 1. group order / perfectness: the cyclic group generated by q1 alone
C = closure([Q1])
comms = {qmul(qmul(a, b), qmul(qinv(a), qinv(b))) for a in C for b in C}
neg('order check "|Gamma| = 120" fails for <q1>', len(C) == 120)
neg('perfectness check fails for <q1>', len(closure(list(comms))) == len(C))

mp.dps = 40
S = Setup('A')
sec = S.sectors['4']
# 2. intertwiner residual with a perturbed eta (1e-20 in one entry)
eta = [row[:] for row in sec.eta[9][0]]
eta[4][1] += mpf(10) ** -20
r = mat_maxdiff(mat_mul(S.D(9, S.idx_q2), eta), mat_mul(eta, sec.sigma[S.idx_q2]))
neg('intertwiner residual < 1e-30 fails for eta perturbed by 1e-20', r < mpf(10) ** -30)
# 3. orthonormality with a rescaled eta'
e2 = [[x * (1 + mpf(10) ** -20) for x in row] for row in sec.eta[9][1]]
r = mat_maxdiff(mat_mul(mat_adj(e2), e2), [[1 if a == b else 0 for b in range(4)] for a in range(4)])
neg('eta^dag eta = I (< 1e-30) fails for eta scaled by 1 + 1e-20', r < mpf(10) ** -30)

# 4. Pi_6 N parallel to Phi fails away from a critical point (item-11 vector), numerically and exactly
num = load_results('numeric')
ex = load_results('exact_su2')
neg('Pi_6 N(Phi) - Q Phi = 0 fails at the item-11 vector (sector 3)',
    num['item11_sector3']['Pi6N_minus_QPhi_norm'] == '0')
neg('exact stationarity of rhat6 fails at the item-11 vector', ex['U5_item11']['stationary'])

# 5. xi covariance with the wrong character (conjugate) at U5
U = fibre_vectors()
et, tx = tangent_vectors(U)
Phi = sec.block(U['U5'])
N = sec.N(Phi)
xi = {J: [vscale(v, -1 / mpf(mu(J))) for v in N[J]] for J in N if J != 3}
g, chi = stabilizer_generators()['U5'][0]
r = sec_maxdiff(left_act(xi, g), sec_scale(xi, mp.conj(chi)))
neg('xi covariance (< 1e-30) fails with the conjugate character', r < mpf(10) ** -30)

# 6. ker L = orbit tangents fails if Q is shifted by 1e-10
res = analyze(S, '4', 'U5', U['U5'], et, tx)
Wn = res['L_eigenvalues']
shifted = [x - mpf(10) ** -10 for x in Wn]
kd = sum(1 for x in shifted if abs(x) < mpf(10) ** -20)
neg('kernel dim = orbit dim fails when L is shifted by 1e-10', kd == res['orbit_tangent_dim'])

# 7. item 12: equation residual with a wrong denominator, and quadrature with a too-coarse grid
with mp.workdps(30):
    S30 = Setup('A')
    s3 = S30.sectors['3']
    U30 = fibre_vectors()
    Phi = s3.block(U30['U1'])
    N = s3.N(Phi)
    xi_bad = {J: [vscale(v, -1 / mpf(mu(J) + 1)) for v in N[J]] for J in N if J != 3}
    worst = mpf(0)
    for J, vs in xi_bad.items():
        lhs = [vadd(minus_laplacian(u, J), u, -48) for u in vs]
        worst = max(worst, tmax(tsub(tensor_of(s3, lhs, J), tensor_of(s3, [vscale(v, -1) for v in N[J]], J))))
    neg('item-12 residual < 1e-25 fails for xi built with n(n+2)-47', worst < REQ)
    coarse = make_grid(8, 5)
    F = project_quadrature(s3, Phi[3][0], coarse)
    diff = max(tmax(tsub(F[J], tensor_of(s3, N.get(J, []), J))) for J in range(10))
    neg('quadrature = algebra (< 1e-25) fails on an 8 x 5 x 8 grid (not exact to spin 18)', diff < REQ)

# 8. identification agreement fails for a value perturbed at the 1e-60 level
with mp.workdps(80):
    s_lo, _ = identify(mpf(1288) / 1287 + mpf(10) ** -60)
with mp.workdps(120):
    s_hi, _ = identify(mpf(1288) / 1287)
neg('identification agreement fails for a 1e-60 perturbation', s_lo is not None and s_lo == s_hi)

# 9. Majorana equivariance fails if g is used instead of g^-1
from s03_stabilizers import roots, same_multiset, rowmul
gr = rot((1, 2, 3), mpf('0.7'))
ut = [mpc(k + 1, 3 - k) for k in range(7)]
with mp.workdps(30):
    neg('Majorana equivariance fails with the wrong map p -> p g',
        same_multiset(roots(mat_vec(wigner_D(6, gr), ut)), [rowmul(p, gr) for p in roots(ut)]))

# 10. the A-versus-B comparison can distinguish different data (U1 vs U2)
r1 = analyze(S, '3', 'U1', U['U1'], et, tx)
r2 = analyze(S, '3', 'U2', U['U2'], et, tx)
neg('A/B comparison (< 1e-30) fails when comparing U1 with U2', abs(r1['Q'] - r2['Q']) < mpf(10) ** -30)

check('all negative controls detected', all(out.values()))
save_results('negative_controls', {k: bool(v) for k, v in out.items()})
