"""Stage 2, task 5 (T.b at U5, exact): the U5 stabilizer is generated by R_z(2 pi/5), acting on
left fibres diagonally by e^{2 pi i m/5}; chi = e^{4 pi i/5}.  So xi is in X_H iff every nonzero left
weight m of xi satisfies m = 2 mod 5.  Checked on my exact xi (all levels, both sectors)."""
import pickle, json

st = pickle.load(open("out/main_all.pkl", "rb"))
res = {}
for d in (3, 4):
    ws = set()
    for J, terms in st[("U5", d)]["xi"].items():
        for x, Y in terms:
            for m in range(2 * J + 1):
                if not x[m].is_zero():
                    ws.add((m - J) % 5)
    res[d] = sorted(ws)
    print(("PASS" if ws == {2} else "FAIL") +
          " U5 s%d: every nonzero left weight of xi is 2 mod 5 (found %s)   [mutant: require 3 mod 5 -> %s]"
          % (d, sorted(ws), "caught" if ws != {3} else "NOT caught"))
json.dump(res, open("out2/u5_weights.json", "w"))
