"""Stage 2, task 5 (E1/E2 support): exact dimension m of the chi-subspace of V_3 for subgroups
generated by exact rotations (entries in Q(i, sqrt2, sqrt3)), and exact membership of u.
For U1, U2 the torus is replaced by the exact elements R_z(pi/2), R_z(pi/3) (weights mod 12 decide);
for U5 no exact generator is available in my field (cos(pi/5) nests a radical): not done exactly."""
import json
from fractions import Fraction as F
from mq import MQ, ZERO, ONE, mq
from su2 import D_exact
from linalg_mq import nullspace

I = MQ.I
h = F(1, 2)
s2h, s3 = MQ.sqrt(F(1, 2)), MQ.sqrt(3)


def rz(c, s):          # R_z(alpha) with cos(alpha/2) = c, sin(alpha/2) = s
    return [[c - I * s, ZERO], [ZERO, c + I * s]]


Rz_pi2 = rz(s2h, s2h)
Rz_pi3 = rz(s3 * h, mq(h))
Rz_2pi3 = rz(mq(h), s3 * h)
Rx_pi = [[ZERO, -I], [-I, ZERO]]
R110_pi2 = [[s2h, -I * s2h * (1 - I) * s2h], [-I * s2h * (1 + I) * s2h, s2h]]
e = lambda k: (mq(h) + I * s3 * h) if k == 1 else None
chi_pi2_U1 = I * (-1)          # e^{3 i pi/2} = -i
chi_pi3_U1 = mq(-1)            # e^{3 i pi/3} = -1
cases = {
    "U1": ([(Rz_pi2, chi_pi2_U1), (Rz_pi3, chi_pi3_U1)], {3: ONE}),
    "U2": ([(Rz_pi2, ONE), (Rz_pi3, ONE), (Rx_pi, mq(-1))], {0: ONE}),
    "U3": ([(Rz_pi2, mq(-1)), (R110_pi2, mq(-1))], {2: ONE, -2: ONE}),
    "U4": ([(Rz_pi3, mq(-1)), (Rx_pi, mq(-1))], {3: ONE, -3: ONE}),
    "U6": ([(Rz_2pi3, ONE), (Rx_pi, mq(-1))], {3: ONE, 0: MQ.sqrt(F(23, 10)), -3: ONE}),
}
out = {}
for name, (gens, uu) in cases.items():
    rows = []
    for g, chi in gens:
        D = D_exact(3, g)
        for i in range(7):
            rows.append([D[i][k].conj() - (chi if i == k else ZERO) for k in range(7)])
    ns = nullspace(rows)
    u = [uu.get(m, ZERO) for m in range(-3, 4)]
    # u in the span: rank of ns + [u] equals len(ns)
    from linalg_mq import rank
    inside = rank([list(v) for v in ns] + [u]) == len(ns)
    # mutant: the conjugate characters
    rows_m = []
    for g, chi in gens:
        D = D_exact(3, g)
        for i in range(7):
            rows_m.append([D[i][k].conj() - (chi.conj() * (-1) if i == k else ZERO) for k in range(7)])
    ns_m = nullspace(rows_m)
    inside_m = rank([list(v) for v in ns_m] + [u]) == len(ns_m) if ns_m else False
    out[name] = {"m": len(ns), "u_in_chi_subspace": inside, "mutant(-conj chi): u inside": inside_m}
    print("%s %s m = %d (exact), u in the chi-subspace: %s   [mutant -conj(chi): u inside -> %s]"
          % ("PASS" if inside and len(ns) == (2 if name == "U6" else 1) else "FAIL", name, len(ns), inside, inside_m))
json.dump(out, open("out2/exact_m.json", "w"), indent=1)
